version: '3.4'
services:

  leprikon:
    image: misli/sevhlidka
    build: .
    depends_on:
      - memcached
      - mysql
      - smtp
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: sevhlidka
      DATABASE_PASSWORD: dbpassword
      DATABASE_USER: sevhlidka
      EMAIL_HOST: smtp
      EMAIL_HOST_PASSWORD: emailpassword
      EMAIL_HOST_USER: sevhlidka
      EMAIL_SUBJECT_PREFIX: '[SEV Hlídka]'
      LEPRIKON_VARIABLE_SYMBOL_EXPRESSION: '50000000 + reg.subject.subject_type_id * 1000000 + (reg.created.year % 100) * 10000 + (reg.id % 10000)'
      MEMCACHED_LOCATION: memcached:11211
      SECRET_KEY: secretkey
      SERVER_EMAIL: '"SEV Hlídka" <vzdelavanisev@zoobrno.cz>'
    ports:
      - 127.0.0.1:10051:80
    volumes:
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - mysql:/var/run/mysqld

  memcached:
    image: memcached

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: sevhlidka
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
      MYSQL_USER: sevhlidka
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: zoobrno.cz
      smtp_user: sevhlidka:emailpassword
    stdin_open: true
    volumes:
      - ./dkim:/etc/opendkim/domainkeys
    tty: true

volumes:
  mysql:
